[[manager.prepend_keymap]]
on  = [ "y" ]
run = ['''
    shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''', "yank"]

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"
