add_newline = false

[character]
success_symbol = '[❯](bold cyan)'
error_symbol = '[✗](bold red) [❯](bold cyan)'

[line_break]
disabled = false

[directory]
truncation_length = 5

[cmd_duration]
min_time = 200
show_milliseconds = true

[golang]
symbol = ' '
style = 'bold 117'

[python]
symbol = ' '
style = 'bold 142'

[lua]
symbol = ' '
style = 'bold 74'

[c]
symbol = '󰙲 '
detect_extensions = ['cpp', 'hpp', 'c', 'h']
style = 'bold 153'
commands = [ [ 'g++', '--version' ], [ 'clang++', '--version' ] ]

[cmake]
symbol = ' '

[rust]
symbol = '󱘗 '
style = 'bold 130'

