import = ["~/.config/alacritty/themes/gruvbox_material.toml"]

[font]
size = 12

normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
opacity = 1
dimensions = { columns = 84, lines = 26 }

